export const CARDS = [
  {
    id: 1,
    name: 'Gunter',
    description: 'Wenk!',
    attack: 1,
    defense: 1,
    cost: 1,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 2,
    name: 'Snail',
    description: 'Always watching...',
    attack: 1,
    defense: 1,
    cost: 1,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 3,
    name: 'Tree Trunks',
    description: 'Wants to bake an apple pie.',
    attack: 0,
    defense: 2,
    cost: 1,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 4,
    name: 'BMO',
    description: 'Who wants to play video games?',
    attack: 1,
    defense: 3,
    cost: 2,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 5,
    name: 'Peppermint Butler',
    description: 'Knows dark magic.',
    attack: 3,
    defense: 1,
    cost: 2,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 6,
    name: 'Neptr',
    description: 'I am a never-ending pie throwing robot.',
    attack: 1,
    defense: 2,
    cost: 2,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 7,
    name: 'Cinnamon Bun',
    description: 'Half-baked but loyal.',
    attack: 1,
    defense: 4,
    cost: 2,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 8,
    name: 'Finn the Human',
    description: 'Mathematical!',
    attack: 3,
    defense: 4,
    cost: 3,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 9,
    name: 'Lumpy Space Princess',
    description: 'Oh my glob.',
    attack: 2,
    defense: 4,
    cost: 3,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 10,
    name: 'Earl of Lemongrab',
    description: 'UNACCEPTABLE!',
    attack: 4,
    defense: 2,
    cost: 3,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 11,
    name: 'Ricardio',
    description: 'The Heart Guy.',
    attack: 2,
    defense: 5,
    cost: 3,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 12,
    name: 'Jake the Dog',
    description: 'A magical dog with the power to stretch, shrink, and change his shape.',
    attack: 4,
    defense: 5,
    cost: 4,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 13,
    name: 'Lady Rainicorn',
    description: 'Speaks only Korean.',
    attack: 4,
    defense: 3,
    cost: 4,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 14,
    name: 'Magic Man',
    description: 'Not a good guy.',
    attack: 5,
    defense: 2,
    cost: 4,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 15,
    name: 'Huntress Wizard',
    description: 'One with nature.',
    attack: 4,
    defense: 3,
    cost: 4,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 16,
    name: 'Princess Bubblegum',
    description: 'The highly intelligent ruler of the Candy Kingdom.',
    attack: 2,
    defense: 7,
    cost: 5,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 17,
    name: 'Ice King',
    description: 'A wizard corrupted by a magical crown that grants him ice powers.',
    attack: 4,
    defense: 5,
    cost: 5,
    traits: [],
    art: '/assets/cards-art/iceking.png',
  },
  {
    id: 18,
    name: 'Flame Princess',
    description: 'Dangerously hot.',
    attack: 6,
    defense: 2,
    cost: 5,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 19,
    name: 'Susan Strong',
    description: 'Strong like muscle!',
    attack: 5,
    defense: 5,
    cost: 5,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 20,
    name: 'Marceline',
    description: 'A thousand-year-old vampire queen who loves playing her bass axe.',
    attack: 6,
    defense: 4,
    cost: 6,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 21,
    name: 'Martin Mertens',
    description: 'Professional deadbeat.',
    attack: 5,
    defense: 4,
    cost: 6,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 22,
    name: 'Prismo',
    description: 'Wishmaster.',
    attack: 0,
    defense: 10,
    cost: 7,
    traits: ['taunt'],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 23,
    name: 'Cosmic Owl',
    description: 'Appears in your dreams.',
    attack: 5,
    defense: 7,
    cost: 8,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },

  {
    id: 24,
    name: 'The Lich',
    description: 'Fall.',
    attack: 8,
    defense: 8,
    cost: 9,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 25,
    name: 'GOLB',
    description: 'Embodiment of chaos.',
    attack: 10,
    defense: 10,
    cost: 10,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
];
