export const CARDS = [
  {
    id: 1,
    name: 'Iron Man',
    description: 'Genius, billionaire.',
    attack: 4,
    defense: 3,
    cost: 3,
    traits: [],
  },
  {
    id: 2,
    name: 'Captain America',
    description: 'First Avenger.',
    attack: 3,
    defense: 5,
    cost: 3,
    traits: ['taunt'],
  },
  {
    id: 3,
    name: 'Thanos',
    description: 'I am inevitable.',
    attack: 8,
    defense: 8,
    cost: 8,
    traits: [],
  },
  {
    id: 4,
    name: 'Spider-Man',
    description: 'Friendly neighborhood.',
    attack: 3,
    defense: 2,
    cost: 2,
    traits: ['dodge'],
  },
  { id: 5, name: 'Hulk', description: 'SMASH!', attack: 6, defense: 6, cost: 6, traits: [] },
  {
    id: 6,
    name: 'Black Widow',
    description: 'Deadly assassin.',
    attack: 4,
    defense: 1,
    cost: 2,
    traits: [],
  },
  {
    id: 7,
    name: 'Thor',
    description: 'God of Thunder.',
    attack: 5,
    defense: 4,
    cost: 5,
    traits: [],
  },
  {
    id: 8,
    name: 'Hawkeye',
    description: 'Never misses.',
    attack: 3,
    defense: 1,
    cost: 2,
    traits: [],
  },
];
