export const CARDS = [
  // ==========================================
  // UNITS (СУЩЕСТВА)
  // ==========================================
  {
    id: 1,
    type: 'unit',
    name: 'Gunter',
    description: 'Wenk!',
    attack: 1,
    defense: 1,
    cost: 1,
    traits: ['charge'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 2,
    type: 'unit',
    name: 'Snail',
    description: 'Always watching...',
    attack: 1,
    defense: 1,
    cost: 1,
    traits: ['poison'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 3,
    type: 'unit',
    name: 'Tree Trunks',
    description: 'Wants to bake an apple pie.',
    attack: 0,
    defense: 4,
    cost: 1,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 4,
    type: 'unit',
    name: 'BMO',
    description: 'Who wants to play video games?',
    attack: 2,
    defense: 3,
    cost: 2,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 5,
    type: 'unit',
    name: 'Peppermint Butler',
    description: 'Knows dark magic.',
    attack: 2,
    defense: 1,
    cost: 2,
    traits: ['poison'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 6,
    type: 'unit',
    name: 'Neptr',
    description: 'I am a never-ending pie throwing robot.',
    attack: 2,
    defense: 2,
    cost: 2,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 7,
    type: 'unit',
    name: 'Cinnamon Bun',
    description: 'Half-baked but loyal.',
    attack: 1,
    defense: 4,
    cost: 2,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 8,
    type: 'unit',
    name: 'Finn the Human',
    description: 'Mathematical!',
    attack: 3,
    defense: 4,
    cost: 3,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 9,
    type: 'unit',
    name: 'Lumpy Space Princess',
    description: 'Oh my glob.',
    attack: 2,
    defense: 4,
    cost: 3,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 10,
    type: 'unit',
    name: 'Earl of Lemongrab',
    description: 'UNACCEPTABLE!',
    attack: 4,
    defense: 2,
    cost: 3,
    traits: ['charge'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 11,
    type: 'unit',
    name: 'Ricardio',
    description: 'The Heart Guy.',
    attack: 2,
    defense: 5,
    cost: 3,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 12,
    type: 'unit',
    name: 'Jake the Dog',
    description: 'A magical dog with the power to stretch, shrink, and change his shape.',
    attack: 3,
    defense: 5,
    cost: 4,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 13,
    type: 'unit',
    name: 'Lady Rainicorn',
    description: 'Speaks only Korean.',
    attack: 4,
    defense: 5,
    cost: 4,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 14,
    type: 'unit',
    name: 'Magic Man',
    description: 'Not a good guy.',
    attack: 3,
    defense: 3,
    cost: 4,
    traits: ['poison'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 15,
    type: 'unit',
    name: 'Huntress Wizard',
    description: 'One with nature.',
    attack: 4,
    defense: 3,
    cost: 4,
    traits: ['charge'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 16,
    type: 'unit',
    name: 'Princess Bubblegum',
    description: 'The highly intelligent ruler of the Candy Kingdom.',
    attack: 2,
    defense: 7,
    cost: 5,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 17,
    type: 'unit',
    name: 'Ice King',
    description: 'A wizard corrupted by a magical crown.',
    attack: 4,
    defense: 6,
    cost: 5,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 18,
    type: 'unit',
    name: 'Flame Princess',
    description: 'Dangerously hot.',
    attack: 5,
    defense: 2,
    cost: 5,
    traits: ['charge'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 19,
    type: 'unit',
    name: 'Susan Strong',
    description: 'Strong like muscle!',
    attack: 6,
    defense: 5,
    cost: 5,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 20,
    type: 'unit',
    name: 'Marceline',
    description: 'A thousand-year-old vampire queen who loves playing her bass axe.',
    attack: 5,
    defense: 6,
    cost: 6,
    traits: ['poison'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 21,
    type: 'unit',
    name: 'Martin Mertens',
    description: 'Professional deadbeat.',
    attack: 5,
    defense: 7,
    cost: 6,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 22,
    type: 'unit',
    name: 'Prismo',
    description: 'Wishmaster.',
    attack: 4,
    defense: 10,
    cost: 7,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 23,
    type: 'unit',
    name: 'Cosmic Owl',
    description: 'Appears in your dreams.',
    attack: 8,
    defense: 8,
    cost: 8,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 24,
    type: 'unit',
    name: 'The Lich',
    description: 'Fall.',
    attack: 8,
    defense: 8,
    cost: 9,
    traits: ['taunt'],
    art: '/assets/cards-art/finn.png',
  },
  {
    id: 25,
    type: 'unit',
    name: 'GOLB',
    description: 'Embodiment of chaos.',
    attack: 12,
    defense: 12,
    cost: 10,
    traits: [],
    art: '/assets/cards-art/finn.png',
  },

  // ==========================================
  // SPELLS (ЗАКЛИНАНИЯ)
  // ==========================================
  {
    id: 26,
    type: 'spell',
    name: "Mabel's Sweater",
    description: 'Grants +1 to your current mana.',
    cost: 1,
    spellEffect: 'add_mana',
    spellValue: 1,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 27,
    type: 'spell',
    name: 'Fireball',
    description: 'Deals 2 damage to any target.',
    cost: 2,
    spellEffect: 'damage',
    spellValue: 2,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 28,
    type: 'spell',
    name: 'Bacon Pancakes',
    description: 'Restores 4 defense to your card.',
    cost: 3,
    spellEffect: 'heal_card',
    spellValue: 4,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 29,
    type: 'spell',
    name: 'The Enchiridion',
    description: 'Grants your card +2 attack and +2 defense.',
    cost: 4,
    spellEffect: 'buff_card',
    spellStats: { attack: 2, defense: 2 },
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
  {
    id: 30,
    type: 'spell',
    name: "Cyclops' Tears",
    description: 'Restores 5 defense to your avatar.',
    cost: 3,
    spellEffect: 'heal_avatar',
    spellValue: 5,
    traits: [],
    art: '/assets/cards-art/bubblegum.png',
  },
];
